### ISSUE TITLE
Self-audit crate with `cargo-vet`

### ISSUE THREAD

**Issue by repi** [EmbarkStudios/presser#6]
We should add a self-audit of this crate to our central audit file in https://github.com/EmbarkStudios/rust-ecosystem/blob/main/audits.toml.

Practically all that is needed is doing a PR to that repo that adds a toml item for the latest version of `presser`, would be nice in the notes of the audit to describe a bit around the unsafe code in this crate, that there are no ambient capabilities or dependencies, and can say that we are using it in production. Can be quite brief though!

See this section about what to think about for the audit: https://mozilla.github.io/cargo-vet/built-in-criteria.html#safe-to-deploy

Self-audit/certification is fine (see [cargo-vet book](https://mozilla.github.io/cargo-vet/curating-your-audit-set.html#self-certification)), but it would be wonderful if we could later also find someone external to audit it also.

**Comment by fu5ha** [comment]
Opened https://github.com/EmbarkStudios/rust-ecosystem/pull/91
